const fs = require('fs');
const path = process.argv[2];
const raw = fs.readFileSync(path, 'utf8');
const probe = '分支 B — 有待刷新目标';
const idx = raw.indexOf(probe);
console.log('分支 B — 有待刷新目标 found at', idx);
console.log(JSON.stringify(raw.slice(idx, idx + 420)));
console.log();
console.log('--- 分支 B-亲密开局分流 ---');
const idx2 = raw.indexOf('分支 B-亲密开局分流');
console.log('found at', idx2);
console.log(JSON.stringify(raw.slice(idx2 - 80, idx2 + 320)));
console.log();
console.log('--- B4a area (task3.promptGroup[2]) NTRS期 bullets ---');
const idx3 = raw.indexOf('- **NTRS期**');
console.log('first - **NTRS期** at', idx3);
console.log(JSON.stringify(raw.slice(idx3, idx3 + 420)));
console.log();
const idx4 = raw.indexOf('- **NTRS期·亲密开局');
console.log('B4a new bullet at', idx4);
console.log(JSON.stringify(raw.slice(idx4, idx4 + 300)));
