const fs = require('fs');
const path = process.argv[2];
const j = JSON.parse(fs.readFileSync(path, 'utf8'));
const obj = Array.isArray(j) ? j[0] : j;
const t1 = obj.plotTasks[1];
const t3 = obj.plotTasks[2];
console.log('=== B1 area: task1.promptGroup[0] bullets mentioning 站队/分流 ===');
const c0 = t1.promptGroup[0].content;
const lines0 = c0.split('\n');
lines0.forEach((l, i) => { if (l.includes('站队') || l.includes('分流') || l.includes('亲密开局')) console.log(i, JSON.stringify(l.slice(0, 260))); });
console.log();
console.log('=== B3 area: task1.description (S2 desc) ===');
console.log(JSON.stringify(t1.description.slice(0, 700)));
console.log();
console.log('=== B5 area: task3.description (S3 desc) contains 亲密开局? ===');
console.log('contains 亲密开局:', t3.description.includes('亲密开局'));
const bi = t3.description.indexOf('NTRS期落实知情度');
console.log(JSON.stringify(t3.description.slice(bi, bi + 400)));
console.log();
console.log('=== check 见 B2 literal in whole file ===');
const blob = JSON.stringify(j);
console.log('contains 见 B2:', blob.includes('见 B2'));
